### ISSUE TITLE
Incorrect handling of `addr:unit` tag

### ISSUE THREAD

**Issue by soshial** [Davis-Klavins/osm-latvia-bot#3]
All address data was removed from [this building](https://www.openstreetmap.org/way/208028376/history) and only `addr:unit` tag is left.

1. Example 1
The address is Maiznīcas iela 8 lit. 2 in Riga. Here's a photo from the place:
![PXL_20220728_170719580](https://user-images.githubusercontent.com/100644/181750525-8d26f3ca-dc82-4f30-b796-c666de355d17.jpg)

2.Example 2
[This building](https://www.openstreetmap.org/way/136427949) should have this address:
![PXL_20220725_073613361](https://user-images.githubusercontent.com/100644/181796297-81e73b6c-fcef-4386-b541-54f0080064d9.jpg)

**Comment by Davis-Klavins** [comment]
A common misinterpretation is to consider address on a plaque instead of the one set by municipalities and managed in the State Address Register as the actual one. In both cases, the same address has been assigned to multiple buildings (check [kadastrs.lv](https://www.kadastrs.lv/#)). Currently, only address points are used to assign addresses (see [Wiki](https://wiki.openstreetmap.org/wiki/Automated_edits/Latvia-bot)):

> Within the State Address Register, location of addresses of buildings and land parcels are defined by point coordinates. One coordinate pair exists per address even if it applies to multiple buildings. Addresses of all buildings and land parcels are defined in the State Immovable Property Cadastre Information System also managed by the State Land Service. At least initially, only point based data from the State Address Register will be used, although at a later stage it might be possible to set addresses for all buildings of certain type that imply and address (e.g., residential) by using [open data](https://data.gov.lv/dati/eng/dataset/kadastra-informacijas-sistemas-atvertie-dati) of the State Immovable Property Cadastre Information System.

addr:unit is "used for ways if building contains no more than one flat and address is assigned to more than one building or building part. Used also for row houses as nodes if building parts are not clearly distinguishable." In the two cases above, multiple flats are located within these buildings. [addr:flats](https://wiki.openstreetmap.org/wiki/Key:addr:flats) should be used instead and it can be later automated for ways (but not for nodes which retain manual editing) using data of the State Immovable Property Cadastre Information System, thus no need to waste time on manual editing. I would suggest deleting these remaining addr:unit tags because they don't relate to units.

"Lit." (_liters_) is not a part of addressing in Latvia at all, although commonly used on plaques in cities, especially Riga and Jūrmala. It means last three digits of the cadastral identifier (_kadastra apzīmējums_) without leading zeroes.

**Comment by soshial** [comment]
Shouldn't then the tag be `addr:housenumber=112/2` and `addr:housenumber=8-2`?

**Comment by Davis-Klavins** [comment]
No, for [208028376](https://www.openstreetmap.org/way/208028376/) (01000230088002) and [208028375](https://www.openstreetmap.org/way/208028375/) (01000230088001) it should be addr:housenumber=8 and for [136427949](https://www.openstreetmap.org/way/136427949/) (01000280014002) and [136428014](https://www.openstreetmap.org/way/136428014/) (01000280014001) addr:housenumber=114. The only difference is in the numbers of flats within each building. Take a look at [kadastrs.lv](https://www.kadastrs.lv/#) (you have to login to see numbers of flats within each building). E.g., for 01000280014002 it would be addr:flats=54-64.

**Comment by soshial** [comment]
1. By the way, the work you're doing is really impressive. May I make a symbolic donation to the cause here on Github or liberapay/opencollective? :) 
2. Are there an plans to incorporate IDs from _Vietvardu datubaze_? At least to start with easy objects like cemeteries and lakes.

**Comment by Davis-Klavins** [comment]
1. Thanks for appreciation! It's a hassle from tax perspective, but I'll accept as a donation to Ukraine instead (e.g., one of [these](https://www.ziedot.lv/?ca=451)).
2. IDs from the Place Names Database I've indeed planned to include, but for isolated dwellings to facilitate updating. Most of isolated dwellings haven't been altered after initial inclusion in OSM, but their position in the Place Names Databases has been improved over years, thus for isolated dwellings whose position haven't been altered within OSM, it can be replaced with the one from the latest version of the Place Names Database.

**Comment by soshial** [comment]
1. I really doubt, that a 20-30 EUR would ever be a problem for tax officials.  But if you would prefer not to take it, that's OK. Thank you a lot anyway!
2. Do you mean that we should not revert edited locations (of already existing OSM point: isolated dwellings and other objects from Place Names Database) back to the data that is in the Place Names Database? What do you think about location coordinates quality of the Place Names Database?

**Comment by Davis-Klavins** [comment]
Yes, because data quality of the Place Names Database is not that good as one might expect, although it has been improved over years. It has been discussed also [here](https://github.com/Davis-Klavins/osm-latvia-bot/issues/2).

**Comment by soshial** [comment]
Thanks for the explanation.

Just an observation: there are quite some villages that are not added to OSM at all, for example this address that you added: https://www.openstreetmap.org/node/9887652742 has `addr:place=Pudinava`, but there is no such place at all in OSM. Is it possible to check approximately, how many such places there are? Where do we take this data: from Place Names Database or another DB?

**Comment by Davis-Klavins** [comment]
Villages need quite an improvement is OSM. There is no single source where all of them are listed, but these can be used:

1. Villages with defined borders from the State Address Register as ways. For these, also the number of population can be obtained from the data [published](https://data.gov.lv/dati/lv/dataset/iedzivotaji/resource/83da473d-68e1-4120-93f4-817bafce88a2) by the Central Statistical Bureau.
2. Villages without defined borders from the State Address Register (called _mazciemi_) as nodes.
3. Remaining villages from the Place Names Database as nodes.

All of theses sources need to be synchronized to facilitate updating similarly as address data is maintained because data changes over time. Data from the Place Names Database needs a closer look to determine if villages really can be used without manual alterations (e.g., coordinates). Likely data of the Place Names Database include villages not existing anymore (might be used as [localities](https://wiki.openstreetmap.org/wiki/Tag:place%3Dlocality), though).
